export {
    createWrapDecorator,
    createEncapsulateDecorator,
    padding,
    curlyBracket,
    roundedBox,
    type Decorator,
    type EncapsulateOption,
    boxChar,
    doubleSquareBox,
    squareBox,
    ASCIIBox,
    multiDecorator,
    encapsulate,
} from "./display/decorate";
